### ISSUE TITLE
Issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by kk-fantasy** [kk-fantasy/originalapp#14]
実装予定の機能
-[] レビュー投稿機能
-[] いいね機能
-[] コメント機能
-[] タグ機能

必要なページ
-[] トップページ
-[] 一覧ページ
-[] 会員登録ページ
-[] ログインページ
-[] パスワード再発行ページ
-[] コンテンツ投稿ページ
-[] コンテンツ詳細ページ
-[] コンテンツ編集ページ
-[] コメント投稿ページ
-[] コメント編集ページ
-[] マイページ

**Comment by kk-fantasy** [comment]
issueベースの開発の提出です。
GitHubProjectのURLです。

https://github.com/users/kk-fantasy/projects/1/views/1?sumFields=%5B114980368%5D&hideItemsCount=false

ご確認よろしくお願いします。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

---

デプロイのカードも作成しましょう。

また、ストーリーポイント5以上を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5以上を付けているように見受けられました。
ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by kk-fantasy** [comment]
すみません。提出するのを忘れていました。
修正をしました。
・デプロイのカードを追加
・ストーリーポイントを見直し、タスクの細分化を行いました。

https://github.com/users/kk-fantasy/projects/1/views/1?sumFields=%5B114980368%5D&hideItemsCount=false

**Comment by ky0613** [comment]
提出ありがとうございます。
以下コメントになります。

----

- デプロイのカードは初めの方に持っていきましょう。（後に回すとどこでエラーになっているか特定するのに時間がかかるため）
- リポジトリへのprojectsの紐付けができていないようなので対応お願いします。

**Comment by kk-fantasy** [comment]
修正しました。
https://github.com/users/kk-fantasy/projects/1/views/1
・デプロイのカードを先頭に持ってくる
・リポジトリへのprojectsの紐付け

よろしくお願いします。

**Comment by tmtkzk0823** [comment]
概ね良さそうです。
LGTMです！
